### ISSUE TITLE
Tile edge removal tests

### ISSUE THREAD

**Issue by bcamper** [tangrams/differ-tests#2]
Example: https://gist.githubusercontent.com/anonymous/efcf9104db529da33bb660816bd65317/raw/1ed64d471f0dac4d564f3d76a4e9155e89f10178/scene.yaml

http://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2Fefcf9104db529da33bb660816bd65317%2Fraw%2F1ed64d471f0dac4d564f3d76a4e9155e89f10178%2Fscene.yaml#15/40.6593/-73.9808

**Comment by bcamper** [comment]
Should probably also have one with `tile_edges: true`

**Comment by meetar** [comment]
fixed with a1e835e79ce9b6990c790b865fc26e49aec28b6b
